"""initial_schema

Revision ID: 45b89c2b5b2b
Revises: 
Create Date: 2026-03-01 21:34:57.295210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45b89c2b5b2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fips_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('state_abbr', sa.String(length=2), nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=False),
    sa.Column('has_scraper', sa.Boolean(), nullable=False),
    sa.Column('scraper_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fips_code')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_frequency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('apn', sa.Text(), nullable=True),
    sa.Column('county_id', sa.BigInteger(), nullable=True),
    sa.Column('address_raw', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_city', sa.Text(), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=5), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('parcel_geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=True),
    sa.Column('year_built', sa.SmallInteger(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('lot_size_sqft', sa.Integer(), nullable=True),
    sa.Column('zoning', sa.Text(), nullable=True),
    sa.Column('assessed_value', sa.BigInteger(), nullable=True),
    sa.Column('market_value', sa.BigInteger(), nullable=True),
    sa.Column('last_sale_date', sa.Date(), nullable=True),
    sa.Column('last_sale_price', sa.BigInteger(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_properties_apn_county', 'properties', ['apn', 'county_id'], unique=True, postgresql_where='apn IS NOT NULL')
    op.create_index('idx_properties_county', 'properties', ['county_id'], unique=False)
    # Spatial indexes on location/parcel_geometry are created automatically by GeoAlchemy2
    op.create_index('idx_properties_updated', 'properties', ['updated_at'], unique=False)
    op.create_index('idx_properties_zip', 'properties', ['address_zip'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('county_id', sa.BigInteger(), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('schedule_cron', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('listing_id', sa.Text(), nullable=True),
    sa.Column('list_price', sa.BigInteger(), nullable=True),
    sa.Column('original_price', sa.BigInteger(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('price_reductions', sa.Integer(), nullable=False),
    sa.Column('listing_status', sa.Text(), nullable=True),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('last_price_cut', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listing_property', 'listing_data', ['property_id'], unique=False)
    op.create_index('idx_listing_source_id', 'listing_data', ['source', 'listing_id'], unique=True, postgresql_where='listing_id IS NOT NULL')
    op.create_table('owners',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=False),
    sa.Column('mailing_address', sa.Text(), nullable=True),
    sa.Column('mailing_city', sa.Text(), nullable=True),
    sa.Column('mailing_state', sa.String(length=2), nullable=True),
    sa.Column('mailing_zip', sa.String(length=5), nullable=True),
    sa.Column('owner_type', sa.Text(), nullable=True),
    sa.Column('is_absentee', sa.Boolean(), nullable=True),
    sa.Column('is_out_of_state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('indicator_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicators_filing_date', 'property_indicators', ['filing_date'], unique=False)
    op.create_index('idx_indicators_property', 'property_indicators', ['property_id'], unique=False)
    op.create_index('idx_indicators_status', 'property_indicators', ['status'], unique=False)
    op.create_index('idx_indicators_type', 'property_indicators', ['indicator_type'], unique=False)
    op.create_table('property_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('indicator_count', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_tier', sa.Text(), nullable=True),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_index('idx_scores_tier', 'property_scores', ['score_tier'], unique=False)
    op.create_index('idx_scores_total', 'property_scores', ['total_score'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=True),
    sa.Column('records_upserted', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_property_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('list_name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', 'list_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_property_lists')
    op.drop_table('scrape_runs')
    op.drop_index('idx_scores_total', table_name='property_scores')
    op.drop_index('idx_scores_tier', table_name='property_scores')
    op.drop_table('property_scores')
    op.drop_index('idx_indicators_type', table_name='property_indicators')
    op.drop_index('idx_indicators_status', table_name='property_indicators')
    op.drop_index('idx_indicators_property', table_name='property_indicators')
    op.drop_index('idx_indicators_filing_date', table_name='property_indicators')
    op.drop_table('property_indicators')
    op.drop_table('owners')
    op.drop_index('idx_listing_source_id', table_name='listing_data', postgresql_where='listing_id IS NOT NULL')
    op.drop_index('idx_listing_property', table_name='listing_data')
    op.drop_table('listing_data')
    op.drop_table('scrape_jobs')
    op.drop_index('idx_properties_zip', table_name='properties')
    op.drop_index('idx_properties_updated', table_name='properties')
    op.drop_index('idx_properties_county', table_name='properties')
    op.drop_index('idx_properties_apn_county', table_name='properties', postgresql_where='apn IS NOT NULL')
    op.drop_table('properties')
    op.drop_table('saved_searches')
    op.drop_table('counties')
    # ### end Alembic commands ###
